var words=['this','thing','sometimes','break','went','can\'t','been','question','quite','quit','from','form','forever','angry','limit','lucky','hours','records','oil','feed','won\'t','its','it\'s','old','many','place','time','experience','time','quest','just','computer','move','white','green','black','orange','different','hour','big','even','mountain','been','animal','long','after','page','tree','see','seen','right','left','has','went','above','said','good','long','it','why','that','learn','girl','boy','will','three','before','may','to','fine','flower','city','street'];var output=document.querySelector('.output');var input=document.querySelector('.type-word');var error_list=document.querySelector('.incorrect');var refresh=document.querySelector('.refresh');var counter=document.querySelector('.count-down');var result=document.querySelector('.result');var error='padding: 5px 10px; color: #fc5558;';var error_colour='color: #fc5558;';var curr_word='padding: 0 10px; border-bottom: 2px solid rgba(85, 177, 252, .2); background-color: orange;color: rgb(36 76 108); border-top-right-radius: 2px; border-top-left-radius: 2px;';var letter_error='color: #fc5558;';var correct='color: #039303;';var padding='padding: 5px 10px;';var partial='color: #9555fc;';wrd_num=9;input.focus();function word_list(line_num,word_num){var words_list=[];for(let i=0;i<line_num;i++){words_list.push([]);if(words_list.length===line_num){for(let x=0;x<words_list.length;x++){for(let j=0;j<word_num;j++){var rand_num=Math.floor(Math.random()*words.length-1)+1;words_list[x].push(words[rand_num])}}}}
var repeats=[];var search=0;var line_search=0;for(let i=0;i<words_list.length;i++){repeats.push([]);for(let x=0;x<words_list[i].length;x++){if(x===1){repeats[i].push(words_list[i].indexOf(words_list[i][search]))}
if(x===words_list[i].length-1&&search!==words_list[i].length-1){search++;x=0}}
search=0}
for(let i=0;i<repeats.length;i++){for(let x=0;x<repeats[i].length;x++){var rand_num=Math.floor(Math.random()*words.length-1)+1;if(repeats[i][x]<x){words_list[i][x]=words[rand_num]}}}
for(let i=0;i<words_list.length;i++){var line=document.createElement('div');line.setAttribute('class','word-line');for(let x=0;x<words_list[i].length;x++){var span=document.createElement('span');span.setAttribute('class','word');span.style.cssText=padding;line.appendChild(span);for(let j=0;j<words_list[i][x].length;j++){span.innerHTML+='<span class="word-letter">'+words_list[i][x][j]+'</span>'}}
output.appendChild(line)}}
word_list(3,wrd_num);output.querySelectorAll('.word-line')[0].querySelectorAll('.word')[0].style.cssText=curr_word;var word_num=0;function reset_test(e){output.innerHTML='';word_list(3,wrd_num);input.value='';input.focus();error_list.innerHTML='';counter.textContent='60';var key_pressed=document.onkeydown=init_counter;word_num=0}
refresh.addEventListener('click',reset_test);var correct_wrds=0;var letter=0;var correct_letter=0;var incorrect_letter=0;var stroke=0;var letter_stroke=0;var mostly_correct=0;var fully_correct=0;var letter_flow=0;var incorrect_wrd=0;let wrng=[];let wrngUpd=JSON.parse(localStorage.getItem("CrctAndTyp"));if(wrngUpd==null){console.log("LOC Storage Is Empty")}else{wrng=wrngUpd}
function word_check(e){var target=e.target;var letters=target.value;var line=output.querySelectorAll('.word-line')[0];var word_elem=line.querySelectorAll('.word');var word_letters=line.querySelectorAll('.word')[word_num].textContent.split('');var word_inner=line.querySelectorAll('.word')[word_num].querySelectorAll('.word-letter');var word=line.querySelectorAll('.word')[word_num].textContent;var letter_length=letters.replace(/\s/g,'').length;var first_word=word_letters.splice(0,letter_length).toString().replace(/,/g,'');var input_val=letters.split('').toString().replace(/,/g,'').replace(/\s/g,'');if(e.type==='keydown'){if(e.keyCode!==32&&e.keyCode===8){letter--;if(letter<0){letter=0}}else if(e.keyCode!==32&&e.keyCode!==8){letter++}}
if(e.keyCode!==32&&input.value.length<=0){letter=0}else if(e.keyCode!==32&&letter>word_inner.length){letter=word_inner.length}else if(!input.value.match(/\s/)&&input.value.length>0&&e.keyCode!==32){letter=input.value.length}
if(e.keyCode!==32&&e.keyCode===8){if(word_inner[letter]&&word_inner!==undefined){word_inner[letter].removeAttribute('style')}}
if(e.keyCode!==32&&e.keyCode!==8&&word_inner[letter-1]&&word_inner!==undefined){if(first_word===input_val||first_word[letters.length-1]===letters[letters.length-1]){if(e.type==='input'&&e.keyCode!==8||e.type==='input'&&e.keyCode!==32){word_inner[letter-1].style.cssText=correct;correct_letter++;stroke++;letter_stroke++;input.removeAttribute('style');if(stroke===5){correct_wrds++;letter_flow++}}}else if(first_word!==input_val){let letter_join=word_letters.join('');let word_stat_obj={"Correct Word: ":first_word+letter_join,"Typed Word: ":input_val};wrng.push(word_stat_obj);const jsonString=JSON.stringify(wrng);localStorage.setItem('CrctAndTyp',jsonString);word_inner[letter-1].style.cssText=letter_error;if(e.type==='input'&&e.keyCode!==8||e.type==='input'&&e.keyCode!==32){incorrect_letter++;if(correct_letter<=0){correct_letter=0}
stroke=0;input.style.cssText=error_colour}}}
if(e.keyCode!==32&&letter===0){for(let i=0;i<word_inner.length;i++){word_inner[i].removeAttribute('style')}}
line.querySelectorAll('.word')[word_num].style.cssText=curr_word;if(e.type==='keyup'||e.type==='keydown'){word_submit(target,e,letters,line,word_letters,word_inner,word,letter_length,first_word,input_val,word_elem)}}input.addEventListener('input',word_check);input.addEventListener('keyup',word_check);input.addEventListener('keydown',word_check);function word_submit(target,e,letters,line,word_letters,word_inner,word,letter_length,first_word,input_val,word_elem){if(e.keyCode===32&&target.value.match(/\S/)&&target.value[0]!==' '){var correct_size=word_elem[word_num].textContent.length-correct_letter;if(word!==input_val){line.querySelectorAll('.word')[word_num].style.cssText=error;if(correct_size<=correct_letter){correct_wrds++;mostly_correct++;for(let i=0;i<word_elem[word_num].querySelectorAll('span').length;i++){if(word_elem[word_num].querySelectorAll('span')[i].style.color!=='rgb(252, 85, 88)'){word_elem[word_num].querySelectorAll('span')[i].style.cssText=partial;continue}}}else if(incorrect_letter>correct_letter){incorrect_wrd++}
incorrect_letter=0;correct_letter=0}else if(first_word===input_val){correct_wrds++;fully_correct++;line.querySelectorAll('.word')[word_num].style.cssText='padding: 5px 10px; background-color: transparent;'}
word_num++;incorrect_letter=0;correct_letter=0;target.value='';letter=0;if(word_num===line.querySelectorAll('.word').length){line.remove();word_num=0;word_list(1,wrd_num)}}else if(e.keyCode===32&&target.value.match(/\s/)&&!target.value.match(/\s\S/)){target.value='';target.removeAttribute('style')}else if(e.keyCode===32&&target.value.match(/\s\S/)){target.value=target.value.replace(/\s/,'')}}
var timer_size=100;let accuracy;var key_pressed=document.onkeydown=init_counter;var timer_bar=document.querySelector('.timer');function init_counter(e){if(e.keyCode!==32||e.keyCode!==9||e.keyCode!==17||e.keyCode!==18){document.onkeydown=null;var i=60;var counter_start=setInterval(()=>{i--;timer_size--;timer_size=timer_size-.67;if(timer_size<=0){timer_bar.style.cssText='width: 0;'}else{timer_bar.style.cssText='width: '+timer_size+'%;'}
if(i<=0){clearInterval(counter_start);function roundTo(num,digits){const factor=10**digits;return Math.round(num*factor)/factor}
accuracy=roundTo(((correct_wrds-incorrect_wrd)/correct_wrds)*100,0);let backupCrctWrds=correct_wrds;let minusWords=incorrect_wrd+mostly_correct;correct_wrds=roundTo((accuracy/100)*backupCrctWrds,0)-minusWords;let comment="";if(correct_wrds>=0&correct_wrds<20){comment="Very slow typing speed, may need to focus on improving typing skills."}else if(correct_wrds>=20&correct_wrds<=40){comment="Average typing speed, but may still benefit from additional practice."}else if(correct_wrds>40&correct_wrds<=60){comment="Above-average typing speed, can handle most typing tasks efficiently."}else if(correct_wrds>60&correct_wrds<=80){comment="Excellent typing speed, can complete tasks quickly and accurately."}else if(correct_wrds>80&correct_wrds<100){comment="Exceptional typing speed, can handle complex typing tasks with ease."}else if(correct_wrds>=100){comment="Elite typing speed, may be able to type as fast as or faster than professional typists."}
let txt=`
                <div class="typing-div">
                <h1>${comment}</h1>
              </div>          
              <div class="card">                        
                <div class="card_header">
                  <span></span>
                  <h3>Results</h3>
                </div>
              <div class="card-body">
                  <h5 class="card-title">Speed: ${correct_wrds}WPM</h5>              
              </div>
              <div class="card-body">
                  <h5 class="card-title">Accuracy: ${accuracy}%</h5>              
              </div>
              <div class="card-body">
                  <h5 class="card-title">Incorrect Words: ${incorrect_wrd}</h5>              
              </div>
              <div class="social-icons">
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fas fa-envelope"></i></a>
              </div>
              </div>
                        `;result.innerHTML=txt;let loc_arr=[];let update=JSON.parse(localStorage.getItem("myArray"));if(update==null){console.log("LOC STORAGE IS EMPTY")}else{loc_arr=update}
let result_obj={correct_words:correct_wrds,accuracy:accuracy,incorrect_words:incorrect_wrd,mostly_correct:mostly_correct,fully_correct:fully_correct,keystrokes:letter_stroke}
loc_arr.push(result_obj);localStorage.setItem("myArray",JSON.stringify(loc_arr));let storedArray=JSON.parse(localStorage.getItem("myArray"));console.log(storedArray)}
counter.textContent=i},1000)}
function reset_timer(){output.querySelectorAll('.word-line')[0].querySelectorAll('.word')[0].style.cssText=curr_word;timer_size=100;timer_bar.style.cssText='width: 100%;';clearInterval(counter_start);result.innerHTML="";correct_wrds=0;letter=0;incorrect_letter=0;correct_letter=0;letter_stroke=0;mostly_correct=0;fully_correct=0;letter_flow=0;input.removeAttribute('style')}
refresh.addEventListener('click',reset_timer)}